"""users table

Revision ID: 4b26a2018908
Revises: 
Create Date: 2020-02-19 12:32:19.651576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b26a2018908'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('public_key', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(length=120), nullable=False),
    sa.Column('author', sa.String(length=120), nullable=True),
    sa.Column('doc_hash', sa.String(length=120), nullable=True),
    sa.Column('tx_hash', sa.String(), nullable=True),
    sa.Column('sign', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('app_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.Text(), nullable=True),
    sa.Column('Token', sa.Text(), nullable=True),
    sa.Column('TimeLife', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Text(), nullable=True),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('date', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('revoked_tokens')
    op.drop_table('logs')
    op.drop_table('created_users')
    op.drop_table('app_token')
    # ### end Alembic commands ###
